######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 29 19:34:52 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ai.h board.h field.h
FORMS += field.ui
SOURCES += ai.cpp board.cpp field.cpp main.cpp
RESOURCES += resources.qrc
